# Generated by Django 3.0.7 on 2020-07-01 12:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('idx', '0002_auto_20200630_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='название блока'),
        ),
        migrations.AlterField(
            model_name='block',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
