# Generated by Django 3.0.7 on 2020-07-07 17:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('idx', '0003_auto_20200701_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='description',
        ),
        migrations.AlterField(
            model_name='block',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
