# Generated by Django 3.0.7 on 2020-07-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idx', '0004_auto_20200707_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='endwork',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='startwork',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
