# Generated by Django 3.0.6 on 2020-07-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idx', '0006_auto_20200708_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название блока')),
                ('slug', models.SlugField(max_length=200, verbose_name='тег для ид блока')),
                ('idsort', models.PositiveSmallIntegerField(default='1', verbose_name='счетчик сортировки')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
