# Generated by Django 3.0.6 on 2020-07-08 16:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('idx', '0007_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Наполнение'),
        ),
    ]
