# Generated by Django 3.0.7 on 2020-07-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idx', '0008_contacts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='idsort',
            field=models.PositiveSmallIntegerField(default='1', verbose_name='счетчик сортировки'),
        ),
    ]
