# Generated by Django 3.0.6 on 2020-07-13 13:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('idx', '0010_auto_20200713_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Наполнение'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='content_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Наполнение'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='content_ua',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Наполнение'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='idsort_en',
            field=models.PositiveSmallIntegerField(default='1', null=True, verbose_name='счетчик сортировки'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='idsort_ru',
            field=models.PositiveSmallIntegerField(default='1', null=True, verbose_name='счетчик сортировки'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='idsort_ua',
            field=models.PositiveSmallIntegerField(default='1', null=True, verbose_name='счетчик сортировки'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название блока'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название блока'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='name_ua',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название блока'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='slug_en',
            field=models.SlugField(max_length=200, null=True, verbose_name='тег для ид блока'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='slug_ru',
            field=models.SlugField(max_length=200, null=True, verbose_name='тег для ид блока'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='slug_ua',
            field=models.SlugField(max_length=200, null=True, verbose_name='тег для ид блока'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название блока'),
        ),
    ]
