# Generated by Django 3.0.6 on 2020-07-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idx', '0011_auto_20200713_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name_en',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name_ru',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name_ua',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Название блока'),
        ),
    ]
