# Generated by Django 3.0.6 on 2020-07-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idx', '0012_auto_20200713_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='idsort_en',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='idsort_ru',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='idsort_ua',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='slug_ua',
        ),
    ]
