# Generated by Django 3.0.6 on 2020-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idx', '0013_auto_20200713_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name_ua',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Название блока'),
        ),
    ]
