# Generated by Django 3.0.6 on 2020-07-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idx', '0014_auto_20200713_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='content_ua',
            new_name='content_uk',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='name_ua',
        ),
        migrations.AddField(
            model_name='contacts',
            name='name_uk',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name_en',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name_ru',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Название блока'),
        ),
    ]
