# Generated by Django 3.0.7 on 2020-07-13 18:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('idx', '0015_auto_20200713_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Наполнение'),
        ),
        migrations.AddField(
            model_name='block',
            name='content_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Наполнение'),
        ),
        migrations.AddField(
            model_name='block',
            name='content_uk',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Наполнение'),
        ),
        migrations.AddField(
            model_name='block',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название блока'),
        ),
        migrations.AddField(
            model_name='block',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название блока'),
        ),
        migrations.AddField(
            model_name='block',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название блока'),
        ),
    ]
