# Generated by Django 3.0.7 on 2020-07-13 19:04

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('idx', '0016_auto_20200713_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloks', to='idx.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='block',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloks', to='idx.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='block',
            name='category_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloks', to='idx.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='block',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Наполнение'),
        ),
        migrations.AlterField(
            model_name='block',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Наполнение'),
        ),
        migrations.AlterField(
            model_name='block',
            name='content_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Наполнение'),
        ),
        migrations.AlterField(
            model_name='block',
            name='content_uk',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Наполнение'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name_en',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name_ru',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name_uk',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Название блока'),
        ),
    ]
